### ISSUE TITLE
[Change request] Un-scheduling "rules refresh" is possible from admin grid

### ISSUE THREAD

**Issue by FredRaym** [Smile-SA/magento2-module-elasticsuite-virtual-attribute#1]
Today it is possible to mass schedule the refresh of several rules from admin/smile_elasticsuite_virtual_attribute/rule/index.

Could you please add a "Cancel refresh" option in the action list, so that it cancels the refresh process for selected rules ?

Thanks !

**Comment by romainruaud** [comment]
I'm not sure to understand the Use case ? 

Why would you prevent refreshing of a rule ? It could be "dangerous" because the user may forgot he has done this and this would prevent any future refresh of this rule (except if the rule gets edited another time).

Regards

**Comment by FredRaym** [comment]
When contributing on a "live" website, it may be interesting to be able to cancel (rather than to delete) a scheduled rule when you realize you have made a mistake, or you dont want that rule to be applied right now.
The idea is not to change default behaviour (refresh on create) but to give a tool when you dont want to run immediatly the refresh process for a given rule.
Perhaps adding a specific status (ie Canceled) for concerned rules could prevent from forgotting the cancellation, but it is not mandatory from my point of view.

Regards
